development:
  adapter: postgresql
  database: grocery
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: grocery_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: grocery_production
  pool: 5
  timeout: 5000
